export const enum ASSISTENCE_VALUES {
  EMPTY = "",
  ASSISTED = ".",
  NOT_ASSISTED = "F",
  IS_LATE = "T",
  IS_JUSTIFIED = "J",
  OTHER = "U",
}

export const ASSISTENCE_TYPES = [
  ASSISTENCE_VALUES.EMPTY,
  ASSISTENCE_VALUES.ASSISTED,
  ASSISTENCE_VALUES.NOT_ASSISTED,
  ASSISTENCE_VALUES.IS_LATE,
  ASSISTENCE_VALUES.IS_JUSTIFIED,
  ASSISTENCE_VALUES.OTHER,
];
